### ISSUE TITLE
Did you have example for react?

### ISSUE THREAD

**Issue by aligos** [ryanswapp/ryanswapp-url-shortener#2]

**Comment by ryanswapp** [comment]
No I don't. However, url shorteners are all router/server based so your view layer shouldn't even come into the picture. This is an old module that depends on Iron Router so it won't work so well with a React app. I'd recommend checking out the routes and the meteor methods and then just implementing it to fit your particular needs. Let me know if you have any questions about setting it up!

**Comment by aligos** [comment]
Thank's, i will try
